#pragma once
#ifndef BRICK_PANEL480_ENABLE_DISPLAY
#define BRICK_PANEL480_ENABLE_DISPLAY 1
#endif
#ifndef BRICK_PANEL480_ENABLE_TOUCH
#define BRICK_PANEL480_ENABLE_TOUCH 1
#endif
#ifndef BRICK_PANEL480_ENABLE_SD
#define BRICK_PANEL480_ENABLE_SD 0
#endif
#ifndef BRICK_PANEL480_ENABLE_LOGGING
#define BRICK_PANEL480_ENABLE_LOGGING 1
#endif
#ifndef BRICK_PANEL480_LOG_LEVEL
#define BRICK_PANEL480_LOG_LEVEL 0
#endif
